### ISSUE TITLE
How can this be used with gulp?

### ISSUE THREAD

**Issue by JacobDB** [aroneous/stream-consume#4]
I've tried simply using `.pipe(consume());`, but that returns an error:

    (node:2189) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'readable' of undefined
        at Object.module.exports [as consume] (/mnt/c/Users/Jacob/Repositories/new-site/node_modules/stream-consume/i
    ndex.js:2:16)
        at Object.upload (/mnt/c/Users/Jacob/Repositories/new-site/gulp-tasks/upload.js:33:27)
        at config_module.config.then (/mnt/c/Users/Jacob/Repositories/new-site/gulpfile.js:195:34)
        at <anonymous>
    (node:2189) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwi
    ng inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
    (). (rejection id: 1)
    (node:2189) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rej
    ections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by JacobDB** [comment]
Figured it out:

    .pipe(through.obj((file, enc, next) => {
        next(null, consume(file));
    }));
